### ISSUE TITLE
UPnP server icon flickers

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#18]
When starting YAACC 2.1.1 the first time (or after deleting all files via the android app settings), my Gerbera UPnP server in the "sender" tab is shown - but its icon flickers between the default server icon and the custom icon that Gerbera sends, for approximately 10 seconds.

Log: [yaacc-iconflicker-startup.log](https://github.com/tobexyz/yaacc-code/files/2742681/yaacc-iconflicker-startup.log)

----

Also when YAACC is just open and the "sender" tab active, the icon flickers from the gerbera icon, to the default icon, and back - approximately every 30 seconds.

Strangely the log shows an update of one of my UPnP renderers when the icon flickers:

```
D de.yaacc.upnp.UpnpClient: remoteDeviceUpdated: Ivo Clarysse, Henner Zeller gmediarender 2017-12-10_704b182
D de.yaacc.upnp.UpnpClient: remoteDeviceUpdated: Ivo Clarysse, Henner Zeller gmediarender 2017-12-10_704b182
D de.yaacc.browser.BrowseDeviceAdapter: Device icon uri:http://192.168.3.3:49152/icons/mt-icon48.png
D de.yaacc.util.image.ImageDownloader: retrieveImage size:48x48
D de.yaacc.util.image.ImageDownloader: Start load: 1547068463427
D de.yaacc.upnp.UpnpClient: remoteDeviceUpdated: Ivo Clarysse, Henner Zeller gmediarender 2017-12-10_704b182
D de.yaacc.browser.BrowseDeviceAdapter: Device icon uri:http://192.168.3.3:49152/icons/mt-icon48.png
D de.yaacc.util.image.ImageDownloader: Stop load: 1547068463476
D de.yaacc.util.image.ImageDownloader: InputStream: buffer(com.android.okhttp.internal.http.HttpConnection$FixedLengthSource@50ef9a6).inputStream()
D de.yaacc.util.image.ImageDownloader: displaying image size width, height, inSampleSize 48,48,0
D de.yaacc.util.image.ImageDownloader: free memory before image load: 0
D de.yaacc.upnp.UpnpClient: remoteDeviceUpdated: Ivo Clarysse, Henner Zeller gmediarender 2017-12-10_704b182
D de.yaacc.upnp.UpnpClient: remoteDeviceUpdated: Ivo Clarysse, Henner Zeller gmediarender 2017-12-10_704b182
D de.yaacc.upnp.UpnpClient: remoteDeviceUpdated: Ivo Clarysse, Henner Zeller gmediarender 2017-12-10_704b182
D de.yaacc.util.image.ImageDownloader: free memory after image load: 0
D de.yaacc.browser.BrowseDeviceAdapter: Device icon uri:http://192.168.3.3:49152/icons/mt-icon48.png
```

**Comment by tobexyz** [comment]
this is an old bug indeed. I haven't focused it yet because it was of low priority for me. But you are right it should be fixed.

**Comment by tobexyz** [comment]
I've just released version 2.2.0 and it will be available on f-droid in a few days. The bug will be fixed then a bit. The icon will as often repainted as before but only with the same icon. I'll have a deeper look on it when I start the work on #20

**Comment by cweiske** [comment]
It still flickers with 2.2.0, but now it flickers between no icon and the server's icon :)

**Comment by tobexyz** [comment]
that's the expected behaviour at the moment :) the server list is refreshed very often and I haven't yet figured out how to prevent it. So I decided only to prevent a changing icon at the moment

**Comment by cweiske** [comment]
The problem still happens with commit a2e137c (branch `fixes_and_versions`)

**Comment by tobexyz** [comment]
confirmed...

**Comment by tobexyz** [comment]
hopefully fixed now. Please validate by yourself with version 3.0.0

**Comment by cweiske** [comment]
The issue is indeed fixed - the server icon does not flicker anymore. Thank you!
